export const data = {
  programs: [
    {
      name: "hrt 1",
      broadcasted: [
        {
          id: 100,
          name: "Nema informacija",
          startTime: new Date().setHours(1),
          endTime: new Date().setHours(18, 17),
          category: "nema informacija",
        },
        {
          id: 1,
          name: "Potjera",
          startTime: new Date().setHours(18, 17),
          endTime: new Date().setHours(19),
          description:
            "U 'Potjeri' četiri natjecatelja odgovaraju na pitanja općeg znanja i istovremeno grade taktiku koja će ih dovesti do finalnog kruga. Međutim, na putu im stoji Lovac. Taj će (ne)uobičajeni protivnik u uzbudljivoj igri znanja i brzine pokušati natjecatelje, jednog po jednog, izbaciti iz igre i onemogućiti ih da osvoje desetke tisuća kuna.",
          category: "zabavan program",
          isReplay: false,
          score: 4.8,
          img: "https://mojtv.hr/thumb.ashx?path=/images/846c5f56-60a0-412c-9106-f3fe0c7697cb.jpg&w=491&h=250",
        },
        {
          id: 2,
          name: "Dnevnik 2",
          startTime: new Date().setHours(19),
          endTime: new Date().setHours(20, 19),
          description:
            "Najvažnije vijesti iz zemlje i svijeta, brojne reportaže, gostovanja istaknutih stručnjaka i komentatora u Dnevniku 2, u najgledanijoj informativnoj emisiji HTV-a. Uz sportske aktualnosti pogledajte i detaljnu vremensku prognozu za sljedeće dane.",
          category: "informativan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/4637d205-88ac-4810-b163-56a1b5f80655.jpg&w=491&h=250",
        },
        {
          id: 3,
          name: "What's up Sjever-Jug",
          startTime: new Date().setHours(20, 19),
          endTime: new Date().setHours(21, 15),
          description:
            "Kada su se u 19. stoljeću razdvajale Danska i Norveška, vojno jača Danska dobila je Grenland, ledeni otok, ali ipak čvrsto tlo, dok je Norveškoj pripalo Sjeverno more. Do danas Danci tuguju zbog te podjele. Saznat ćemo o norveškom fondu nafte i plina.",
          category: "dokumentarni program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2024-02/a4437446-9487-4024-ad25-ca4e86.jpg&w=163&h=80",
        },
        {
          id: 4,
          name: "Fortuna",
          startTime: new Date().setHours(21, 15),
          endTime: new Date().setHours(22, 18),
          description:
            "'La Fortuna' je španjolsko-američka pustolovna serija. Mladi diplomat Álex Ventura predvodi misiju čiji je cilj vratiti olupina broda koju je prisvojio lovac na blago Frank Wild.",
          category: "serija",
          season: 1,
          episode: 1,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-08/843950b1-7768-4169-b427-eaf20a.jpg&w=163&h=80",
        },
        {
          id: 5,
          name: "Otvoreno",
          startTime: new Date().setHours(22, 18),
          endTime: new Date().setHours(22, 55),
          description:
            "Od rezerve do pobjednika Dore! Kako je Baby Lasagna u mjesec dana osvojio publiku, uvjerljivo odnio pobjedu i odmah skočio na drugo mjesto na kladionicama? Hvata li Hrvatska s Baby Lasagnom priliku za pobjedu?",
          category: "informativan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/55f20577-aa30-4643-a90e-3c83fe1f9538.jpg&w=163&h=80",
        },
        {
          id: 6,
          name: "Dnevnik 3",
          startTime: new Date().setHours(22, 55),
          endTime: new Date().setHours(23, 18),
          description:
            "Najnovije vijesti iz zemlje i svijeta te sažeta vremenska prognoza za sljedeći dan.",
          category: "informativan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/1a283d73-b0f7-4725-be50-67883ed9215d.jpg&w=163&h=80",
        },
        {
          id: 7,
          name: "Labirint",
          startTime: new Date().setHours(23, 18),
          endTime: new Date().setHours(23, 45),
          description:
            "Cijene stanova lete u nebo. Mnogim su mladim obiteljima vlastiti stambeni kvadrati daleki san. Istodobno, teško se pronalaze povoljni podstanarski stanovi. Tko kupuje skupe stambene kvadrate? Zašto država ne gradi stanove za najam?",
          category: "informativni program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-11/11ba9aaa-7e59-461c-aa28-0a5fb2.jpg&w=163&h=80",
        },
        {
          id: 8,
          name: "Putin: Ruska špijunska priča",
          startTime: new Date().setHours(23, 45),
          endTime: new Date().setHours(25, 41),
          description:
            "U drugoj epizodi dokumentarne serije vidjet ćemo kako je Vladimir Putin stigao u Kremlj kao ranjivi i nepoznati predsjednik kojega su ruski oligarsi htjeli kontrolirati. Otkrit ćemo kako je učvrstio svoju moć te se na kraju okružio kolegama iz KGB-a.",
          category: "dokumentarni program",
          isReplay: true,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2022-03/19a598ff-7868-4b54-9de5-8f52d2.jpg&w=163&h=80",
        },
        {
          id: 9,
          name: "Potjera",
          startTime: new Date().setHours(25, 41),
          endTime: new Date().setHours(26, 30),
          description:
            "U 'Potjeri' četiri natjecatelja odgovaraju na pitanja općeg znanja i istovremeno grade taktiku koja će ih dovesti do finalnog kruga. Međutim, na putu im stoji Lovac. Taj će (ne)uobičajeni protivnik u uzbudljivoj igri znanja i brzine pokušati natjecatelje, jednog po jednog, izbaciti iz igre i onemogućiti ih da osvoje desetke tisuća kuna.",
          category: "zabavan program",
          isReplay: true,
          score: 4.8,
          img: "https://mojtv.hr/thumb.ashx?path=/images/846c5f56-60a0-412c-9106-f3fe0c7697cb.jpg&w=491&h=250",
        },
        {
          id: 10,
          name: "La Promesa",
          startTime: new Date().setHours(26, 30),
          endTime: new Date().setHours(27, 30),
          description:
            "Blanca odlučuje otići s La Promese i upustiti se u novu pustolovinu, ali prije toga želi reći Manuelu nešto važno. A nešto jednako važno želi reći i Jani. Catalina pokušava upravljati imanjem iz sjene, ali radnici nikako ne žele prihvatiti ženu.",
          category: "serija",
          season: 1,
          episode: 114,
          isReplay: true,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-09/058f3981-6cb3-4f71-a098-b342e8.jpg&w=163&h=80",
        },
        {
          id: 100,
          name: "Nema informacija",
          startTime: new Date().setHours(27, 30),
          endTime: new Date().setHours(29, 5),
          category: "nema informacija",
        },
      ],
    },
    {
      name: "hrt 2",
      broadcasted: [
        {
          id: 100,
          name: "Nema informacija",
          startTime: new Date().setHours(1),
          endTime: new Date().setHours(17, 14),
          category: "nema informacija",
        },
        {
          id: 11,
          name: "Dom na kvadrat",
          startTime: new Date().setHours(17, 14),
          endTime: new Date().setHours(17, 47),
          description:
            "Dizajnerica interijera Martina Kordić podučit će nas kako neutralne boje u interijeru učiniti zanimljivijima, a Leon Božić predstavlja idealne biljke za male stanove. Donosimo priču o corienu, inovativnom materijalu koji dizajnerima ostvaruje snove.",
          category: "zabavan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2020-04/a8c062ff-7bda-48ee-aca0-c34887.jpg&w=163&h=80",
        },
        {
          id: 12,
          name: "Istrage prometnih nesreća",
          startTime: new Date().setHours(17, 47),
          endTime: new Date().setHours(18, 48),
          description:
            "Analiziramo najteže nesreće na hrvatskim prometnicama. S prometnim stručnjakom Damirom Novakom komentiramo svakodnevne greške vozača. U rubrici Svjedočanstva donosimo priču Ivane Smrečki.",
          category: "zabavan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2020-03/709be0df-694a-4052-96ea-c6a1c0.jpg&w=163&h=80",
        },
        {
          id: 13,
          name: "Glas domovine",
          startTime: new Date().setHours(18, 48),
          endTime: new Date().setHours(19, 49),
          description:
            "U emisiji: životna i poslovna priča Ante Budana iz slovenskog Kopra; predstavljen Hrvatski iseljenički zbornik, gošća emisije je urednica Matičinog ljetopisa Vesna Kukavica; kako su izgledala pokladna okupljanja bačkih Hrvata.",
          category: "informativan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2665089a-0fee-440a-9259-6e1721d81d3e.jpg&w=163&h=80",
        },
        {
          id: 14,
          name: "Ko te šiša",
          startTime: new Date().setHours(19, 49),
          endTime: new Date().setHours(20, 35),
          description:
            "Dolazi sudbonosni trenutak kad Božica odluči stati na vagu ne bi li vidjela koliko su se isplatili mjeseci odricanja i kompletna promjena energije. Svi se okupe na tom važnom događaju. Kada vidi da je razlika u 3 dekagrama, Božica dobiva slom živaca.",
          category: "zabavavan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/5a664f67-da34-44ef-ad7e-e990cbd60d96.jpg&w=163&h=80",
        },
        {
          id: 15,
          name: "Priroda i prijateljice",
          startTime: new Date().setHours(20, 35),
          endTime: new Date().setHours(21, 29),
          description:
            "Sandi Toksvig i Judi Love, komičarka i televizijska autorica, otići će u Cumbriju i odsjesti u tri spektakularne i jedinstvene kuće. Šetat će dolinama, planinariti brdima i ploviti čamcem na glasovitim jezerima.",
          category: "zabavan program",
          isReplay: true,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2022-11/0ae40e08-d2f5-493a-a382-937230.jpg&w=163&h=80",
        },
        {
          id: 16,
          name: "Veliki bijeg",
          startTime: new Date().setHours(21, 29),
          endTime: new Date().setHours(22, 21),
          description:
            "Druga epizoda dokumentarne serije koja rekonstruira planiranje i provedbu jednog od najhrabrijih pothvata tijekom Drugog svjetskog rata - bijeg iz Stalaga Luft III. Stotine savezničkih vojnika riskirale su život kako bi se suprotstavile Hitleru.",
          category: "informativan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2024-02/badbdc3b-3f76-4892-a76e-529128.jpg&w=163&h=80",
        },
        {
          id: 17,
          name: "1917",
          startTime: new Date().setHours(22, 21),
          endTime: new Date().setHours(24, 20),
          description:
            "Tijekom I. svjetskog rata dva mlada vojnika dobiju naizgled nemoguć zadatak.",
          category: "film",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2019-12/2a9b448c-67ed-4e56-8a54-464d62.jpg&w=163&h=80",
        },
        {
          id: 18,
          name: "Dolina sreće",
          startTime: new Date().setHours(24, 20),
          endTime: new Date().setHours(25, 17),
          description:
            "Catherine doznaje za bolnu izdaju bliske osobe, a Faisal se nalazi pod sve većim pritiskom sa svih strana.",
          category: "serija",
          season: 1,
          episode: 2,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/d2bc7916-bf54-4921-81d0-71dbe6d345fe.jpg&w=163&h=80",
        },
        {
          id: 19,
          name: "Novi stari slučajevi",
          startTime: new Date().setHours(25, 17),
          endTime: new Date().setHours(26, 17),
          description:
            "Tenzije između Neda i Sashe rastu. Prisiljeni su raditi zajedno kad se posumnja da je smrt filmskog kritičara, čije je tijelo pronađeno u kanalu, povezana s 20 godina starim ubojstvom konceptualnog umjetnika Davida Strake. Dok ispituje Strakine koleg.",
          category: "serija",
          season: 1,
          episode: 5,
          isReplay: true,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/6401b6fb-c563-4e0b-baa0-11b70135ccc1.jpg&w=163&h=80",
        },
        {
          id: 20,
          name: "Art a la carte",
          startTime: new Date().setHours(26, 17),
          endTime: new Date().setHours(26, 48),
          description:
            "Više od pukog kulturnog pregleda! Od ponedjeljka do četvrtka, pola sata, uživo pratimo kulturne događaje i fenomene iz likovne umjetnosti, klasične glazbe, književnosti, kazališta, plesa, arhitekture i dizajna, popularne glazbe, filma. Problematizira.",
          category: "informativan program",
          isReplay: true,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2017-10/7e941b00-93c1-4fa7-955b-c3618d.jpg&w=163&h=80",
        },
        {
          id: 100,
          name: "Nema informacija",
          startTime: new Date().setHours(26, 48),
          endTime: new Date().setHours(29, 5),
          category: "nema informacija",
        },
      ],
    },
    {
      name: "nova tv",
      broadcasted: [
        {
          id: 100,
          name: "Nema informacija",
          startTime: new Date().setHours(1),
          endTime: new Date().setHours(17, 34),
          category: "nema informacija",
        },
        {
          id: 21,
          name: "Joker",
          startTime: new Date().setHours(17, 34),
          endTime: new Date().setHours(18, 57),
          description:
            "U drugoj epizodi novog kviza ''Joker'' zaigrat će umirovljenica Doris Vlah iz Opatije. Po struci je trgovkinja, no njezina najveća strast je kuhanje, pa preko ljeta radi i kao privatni chef u vilama.",
          category: "zabavan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-11/4fa3ad33-5654-43dd-841e-324612.jpg&w=163&h=80",
        },
        {
          id: 22,
          name: "Dnevnik Nove TV",
          startTime: new Date().setHours(18, 57),
          endTime: new Date().setHours(20, 30),
          description:
            "Najgledanija središnja informativna emisija u zemlji gledateljima svake večeri donosi najvažnije i najrelevantnije informacije iz zemlje i svijeta. Propušteni Dnevnik Nove TV pogledajte na novatv.hr.",
          category: "informativan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2017-06/11ed05da-0a11-4584-930a-e1e80d.jpg&w=163&h=80",
        },
        {
          id: 23,
          name: "Kumovi",
          startTime: new Date().setHours(20, 30),
          endTime: new Date().setHours(21, 25),
          description:
            "Vedrana se nađe u problemu te je suočena sa teškim odlukama. Nakon mnogo razmišljanja, odlučuje razgovarati i sa Zlatanom, no Zlatan je preduhitri te joj kaže da ide s Terezom u Milano. Anđela pak poludi kad čuje Lucu i Janka da odgađaju vjenčanje.",
          category: "serija",
          season: 3,
          episode: 32,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2022-01/5b9afebf-1d85-44b4-8e77-c55f8c.jpg&w=163&h=80",
        },
        {
          id: 24,
          name: "Zlatni kavez",
          startTime: new Date().setHours(21, 25),
          endTime: new Date().setHours(22, 16),
          description:
            "Nakon niza neočekivanih događaja, Kazim radi veliki preokret. Nakon što majci Esme pozli, Sejran će morati progutati svoj ponos i poći s Feritom koji ju je ponovno čekao cijelu noć.",
          category: "serija",
          season: 2,
          episode: 42,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-05/78fc96b5-e5bf-4b57-b162-f526a2.jpg&w=163&h=80",
        },
        {
          id: 25,
          name: "Oproštajno pismo",
          startTime: new Date().setHours(22, 16),
          endTime: new Date().setHours(23, 25),
          description:
            "U domu obitelji Karli, atmosfera je napeta dok Nevzat i najbliži iščekuju ključne vijesti. Hatidže gubi kontrolu nad svojim osjećajima kada čuje nove informacije, obuzeta nevjerojatnim bijesom. S druge strane, Asli dobiva neočekivano dobre vijesti.",
          category: "serija",
          season: 1,
          episode: 42,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-12/f2a3bf09-809b-4979-9554-304719.jpg&w=163&h=80",
        },
        {
          id: 26,
          name: "Večernje vijesti",
          startTime: new Date().setHours(23, 25),
          endTime: new Date().setHours(24, 12),
          description:
            "Pregled najvažnijih informacija iz zemlje i svijeta gledatelji mogu pratiti u Vijestima u 14 i 17 sati te u Večernjim vijestima. Propuštene Vijesti Nove TV pogledajte na novatv.hr.",
          category: "informativni program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/560cf524-143c-4017-b313-2499256ee903.jpg&w=163&h=80",
        },
        {
          id: 27,
          name: "21 Jump street",
          startTime: new Date().setHours(24, 12),
          endTime: new Date().setHours(25, 54),
          description:
            "Odred mladolikih policajaca ubačen je u srednju školu kako bi stali na kraj moćnom dileru.",
          category: "film",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/93ebe664-27f5-4eb8-87a5-032b7f6fb419.jpg&w=163&h=80",
        },
        {
          id: 28,
          name: "Mjesto usijanja",
          startTime: new Date().setHours(25, 54),
          endTime: new Date().setHours(27, 25),
          description:
            "Neočekivani dvojac mora zajednički nadmudriti zločince i spasiti grad od bombaških napada.",
          category: "program za odrasle",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-01/a28a695a-e7cd-40f4-bebd-a3ef60.jpg&w=163&h=80",
        },
        {
          id: 29,
          name: "Astro savjetnik",
          startTime: new Date().setHours(27, 25),
          endTime: new Date().setHours(28, 25),
          description:
            "Naši voditelji su vrhunski stručnjaci koji su se godinama usavršavali i trenirali svoje prirodno urođene sposobnosti da saznaju istinu za druge ljude!",
          category: "program za odrasle",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/719708dc-9f9d-4cde-a9ee-25fd793edf77.jpg&w=163&h=80",
        },
        {
          id: 30,
          name: "Crna lista",
          startTime: new Date().setHours(28, 25),
          endTime: new Date().setHours(29, 5),
          description: "Tko je na tvojoj crnoj listi?",
          category: "serija",
          season: 5,
          episode: 8,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/fbb8891b-2d47-4dd2-b017-c7806eea057e.jpg&w=163&h=80",
        },
      ],
    },
    {
      name: "rtl",
      broadcasted: [
        {
          id: 100,
          name: "Nema informacija",
          startTime: new Date().setHours(1),
          endTime: new Date().setHours(17, 5),
          category: "nema informacija",
        },
        {
          id: 31,
          name: "Dođi, pogodi, osvoji",
          startTime: new Date().setHours(17, 5),
          endTime: new Date().setHours(17, 55),
          description:
            "Plinko, Jedna je prava, Sreća u vreći ili, pak, Veliko kolo – nema puno Hrvata koji barem jednom ispred malih ekrana zajedno s kandidatima nisu zaigrali ove i mnoge druge dinamične igre te pogađali cijene u game showu 'Dođi, pogodi, osvoji!'",
          category: "zabavan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2021-10/f3bb0740-9bff-418e-8ab5-867387.jpg&w=163&h=80",
        },
        {
          id: 32,
          name: "Večera za 5",
          startTime: new Date().setHours(17, 55),
          endTime: new Date().setHours(19, 4),
          description:
            "Gledatelje očekuje nova porcija domaćih obroka i zanimljivih kulinarskih trikova uz lepezu raskošnih karaktera iz svih dijelova Hrvatske. Kulinarsko putovanje Hrvatskom vodi gledatelje u dvije županiju - Varaždinsku i Međimursku.",
          category: "zabavan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-08/d2fbaa29-7fba-4811-9017-d4fd6b.jpg&w=163&h=80",
        },
        {
          id: 33,
          name: "RTL danas",
          startTime: new Date().setHours(19, 4),
          endTime: new Date().setHours(20, 25),
          description:
            "RTL Danas svakog dana donosi samo aktualne, istinite i objektivne informacije. Uz etablirano uredništvo i voditelje, RTL Danas je prvi, neovisan i nepristran informativni program.",
          category: "informativni program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2017-09/a4e0acfa-d967-4857-93b0-c59326.jpg&w=163&h=80",
        },
        {
          id: 34,
          name: "San snova",
          startTime: new Date().setHours(20, 25),
          endTime: new Date().setHours(21, 11),
          description:
            "Nakon spektakularne pobjede protiv Pučkog klub je u euforiji, ali vijesti vezane za Alena promijenit će atmosferu. Hoće li se Maji vratiti povjerenje u Alena? Mirko se sve dublje zakopava u svojim lažima, a sa sobom povlači i klub. ",
          category: "serija",
          season: 1,
          episode: 4,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-08/8866ee6f-e3a4-4b18-b5b3-8cbf7d.jpg&w=163&h=80",
        },
        {
          id: 35,
          name: "Brak na prvu",
          startTime: new Date().setHours(21, 11),
          endTime: new Date().setHours(22, 22),
          description:
            "Pet je parova na prvoj ceremoniji odluke odlučilo ostati u sociološkom eksperimentu, a na površinu su izašle emocije, simpatije i razočaranja. Klara i Lovre posljednji su par koji će se suočiti sa stručnjacima.",
          category: "zabavan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2020-03/ed67ece0-2c54-43f4-bdc1-48144a.jpg&w=163&h=80",
        },
        {
          id: 36,
          name: "RTL Direkt",
          startTime: new Date().setHours(22, 22),
          endTime: new Date().setHours(23),
          description:
            "Od ponedjeljka do četvrtka u večernjem terminu Mojmira Pastorčić najvažnije dnevne događaje donosi direktno i sa stavom. RTL Direkt je prisutan svugdje i izvještava o svemu, s vama i za vas – naše gledatelje.",
          category: "informativan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2017-09/55b5966a-bef4-4be5-a408-440866.jpg&w=163&h=80",
        },
        {
          id: 37,
          name: "Tightrope (1984)",
          startTime: new Date().setHours(23),
          endTime: new Date().setHours(25, 1),
          description:
            "Policijski detektiv koji živi kao samohrani otac hvata serijskog ubojicu prostitutki.",
          category: "film",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/132b6a30-376e-49cc-ab25-a5b780bed415.jpg&w=163&h=80",
        },
        {
          id: 38,
          name: "Zločinački umovi",
          startTime: new Date().setHours(25, 1),
          endTime: new Date().setHours(25, 47),
          description:
            "Istražitelji su u lovu na serijskog ubojicu na Floridi, čiji je identitet poznat policiji, koja ga nije uspjela uloviti jer stalno mijenja izgled. Takav način djelovanja omogućava mu da bira slučajne žrtve koje onda muči u hotelskim sobama.",
          category: "serija",
          season: 3,
          episode: 5,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2017-06/ff6469a3-3af6-4a34-b437-3025b1.jpg&w=163&h=80",
        },
        {
          id: 39,
          name: "Zločinački umovi",
          startTime: new Date().setHours(25, 47),
          endTime: new Date().setHours(26, 34),
          description:
            "Istražitelji surađuju s CIA-om u njenim uredima u Virginiji kako bi razotkrili izdajicu u srcu organizacije. Curenje informacija stavlja u opasnost ljude na terenu pa je pronalazak „krtice“ hitan prioritet.",
          category: "serija",
          season: 3,
          episode: 6,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2017-06/ff6469a3-3af6-4a34-b437-3025b1.jpg&w=163&h=80",
        },
        {
          id: 40,
          name: "Zločinački umovi",
          startTime: new Date().setHours(26, 34),
          endTime: new Date().setHours(27, 25),
          description:
            "Istražitelji se nalaze na zasluženom odmoru na različitim lokacijama, gdje svaki od njih dobiva poruku od psihotičnog ubojice, opsjednutog legendom o kralju Arthuru te ih izaziva da pronađu i spase osobu koju je on označio kao sljedeću žrtvu.",
          category: "serija",
          season: 3,
          episode: 7,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2017-06/ff6469a3-3af6-4a34-b437-3025b1.jpg&w=163&h=80",
        },
        {
          id: 100,
          name: "Nema informacija",
          startTime: new Date().setHours(27, 25),
          endTime: new Date().setHours(29, 5),
          category: "nema informacija",
        },
      ],
    },
    {
      name: "hrt 3",
      broadcasted: [
        {
          id: 100,
          name: "Nema informacija",
          startTime: new Date().setHours(1),
          endTime: new Date().setHours(18, 17),
          category: "nema informacija",
        },
        {
          id: 41,
          name: "Potjera",
          startTime: new Date().setHours(18, 17),
          endTime: new Date().setHours(19),
          description:
            "U 'Potjeri' četiri natjecatelja odgovaraju na pitanja općeg znanja i istovremeno grade taktiku koja će ih dovesti do finalnog kruga. Međutim, na putu im stoji Lovac. Taj će (ne)uobičajeni protivnik u uzbudljivoj igri znanja i brzine pokušati natjecatelje, jednog po jednog, izbaciti iz igre i onemogućiti ih da osvoje desetke tisuća kuna.",
          category: "zabavan program",
          isReplay: false,
          score: 4.8,
          img: "https://mojtv.hr/thumb.ashx?path=/images/846c5f56-60a0-412c-9106-f3fe0c7697cb.jpg&w=491&h=250",
        },
        {
          id: 42,
          name: "Dnevnik 2",
          startTime: new Date().setHours(19),
          endTime: new Date().setHours(20, 22),
          description:
            "Najvažnije vijesti iz zemlje i svijeta, brojne reportaže, gostovanja istaknutih stručnjaka i komentatora u Dnevniku 2, u najgledanijoj informativnoj emisiji HTV-a. Uz sportske aktualnosti pogledajte i detaljnu vremensku prognozu za sljedeće dane.",
          category: "informativan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/4637d205-88ac-4810-b163-56a1b5f80655.jpg&w=491&h=250",
        },
        {
          id: 43,
          name: "What's up Sjever-Jug",
          startTime: new Date().setHours(20, 22),
          endTime: new Date().setHours(21, 14),
          description:
            "Kada su se u 19. stoljeću razdvajale Danska i Norveška, vojno jača Danska dobila je Grenland, ledeni otok, ali ipak čvrsto tlo, dok je Norveškoj pripalo Sjeverno more. Do danas Danci tuguju zbog te podjele. Saznat ćemo o norveškom fondu nafte i plina.",
          category: "dokumentarni program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2024-02/a4437446-9487-4024-ad25-ca4e86.jpg&w=163&h=80",
        },
        {
          id: 44,
          name: "Fortuna",
          startTime: new Date().setHours(21, 14),
          endTime: new Date().setHours(22, 17),
          description:
            "'La Fortuna' je španjolsko-američka pustolovna serija. Mladi diplomat Álex Ventura predvodi misiju čiji je cilj vratiti olupina broda koju je prisvojio lovac na blago Frank Wild.",
          category: "serija",
          season: 1,
          episode: 1,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-08/843950b1-7768-4169-b427-eaf20a.jpg&w=163&h=80",
        },
        {
          id: 45,
          name: "Otvoreno",
          startTime: new Date().setHours(22, 17),
          endTime: new Date().setHours(22, 54),
          description:
            "Od rezerve do pobjednika Dore! Kako je Baby Lasagna u mjesec dana osvojio publiku, uvjerljivo odnio pobjedu i odmah skočio na drugo mjesto na kladionicama? Hvata li Hrvatska s Baby Lasagnom priliku za pobjedu?",
          category: "informativan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/55f20577-aa30-4643-a90e-3c83fe1f9538.jpg&w=163&h=80",
        },
        {
          id: 46,
          name: "Dnevnik 3",
          startTime: new Date().setHours(22, 54),
          endTime: new Date().setHours(23, 17),
          description:
            "Najnovije vijesti iz zemlje i svijeta te sažeta vremenska prognoza za sljedeći dan.",
          category: "informativan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/1a283d73-b0f7-4725-be50-67883ed9215d.jpg&w=163&h=80",
        },
        {
          id: 47,
          name: "Labirint",
          startTime: new Date().setHours(23, 17),
          endTime: new Date().setHours(23, 45),
          description:
            "Cijene stanova lete u nebo. Mnogim su mladim obiteljima vlastiti stambeni kvadrati daleki san. Istodobno, teško se pronalaze povoljni podstanarski stanovi. Tko kupuje skupe stambene kvadrate? Zašto država ne gradi stanove za najam?",
          category: "informativni program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-11/11ba9aaa-7e59-461c-aa28-0a5fb2.jpg&w=163&h=80",
        },
        {
          id: 48,
          name: "Putin: Ruska špijunska priča",
          startTime: new Date().setHours(23, 45),
          endTime: new Date().setHours(25, 40),
          description:
            "U drugoj epizodi dokumentarne serije vidjet ćemo kako je Vladimir Putin stigao u Kremlj kao ranjivi i nepoznati predsjednik kojega su ruski oligarsi htjeli kontrolirati. Otkrit ćemo kako je učvrstio svoju moć te se na kraju okružio kolegama iz KGB-a.",
          category: "dokumentarni program",
          isReplay: true,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2022-03/19a598ff-7868-4b54-9de5-8f52d2.jpg&w=163&h=80",
        },
        {
          id: 9,
          name: "Potjera",
          startTime: new Date().setHours(25, 40),
          endTime: new Date().setHours(26, 30),
          description:
            "U 'Potjeri' četiri natjecatelja odgovaraju na pitanja općeg znanja i istovremeno grade taktiku koja će ih dovesti do finalnog kruga. Međutim, na putu im stoji Lovac. Taj će (ne)uobičajeni protivnik u uzbudljivoj igri znanja i brzine pokušati natjecatelje, jednog po jednog, izbaciti iz igre i onemogućiti ih da osvoje desetke tisuća kuna.",
          category: "zabavan program",
          isReplay: true,
          score: 4.8,
          img: "https://mojtv.hr/thumb.ashx?path=/images/846c5f56-60a0-412c-9106-f3fe0c7697cb.jpg&w=491&h=250",
        },
        {
          id: 50,
          name: "La Promesa",
          startTime: new Date().setHours(26, 30),
          endTime: new Date().setHours(27, 30),
          description:
            "Blanca odlučuje otići s La Promese i upustiti se u novu pustolovinu, ali prije toga želi reći Manuelu nešto važno. A nešto jednako važno želi reći i Jani. Catalina pokušava upravljati imanjem iz sjene, ali radnici nikako ne žele prihvatiti ženu.",
          category: "serija",
          season: 1,
          episode: 114,
          isReplay: true,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-09/058f3981-6cb3-4f71-a098-b342e8.jpg&w=163&h=80",
        },
        {
          id: 100,
          name: "Nema informacija",
          startTime: new Date().setHours(27, 30),
          endTime: new Date().setHours(29, 5),
          category: "nema informacija",
        },
      ],
    },
    {
      name: "hrt 4",
      broadcasted: [
        {
          id: 100,
          name: "Nema informacija",
          startTime: new Date().setHours(1),
          endTime: new Date().setHours(17, 14),
          category: "nema informacija",
        },
        {
          id: 51,
          name: "Dom na kvadrat",
          startTime: new Date().setHours(17, 14),
          endTime: new Date().setHours(17, 47),
          description:
            "Dizajnerica interijera Martina Kordić podučit će nas kako neutralne boje u interijeru učiniti zanimljivijima, a Leon Božić predstavlja idealne biljke za male stanove. Donosimo priču o corienu, inovativnom materijalu koji dizajnerima ostvaruje snove.",
          category: "zabavan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2020-04/a8c062ff-7bda-48ee-aca0-c34887.jpg&w=163&h=80",
        },
        {
          id: 52,
          name: "Istrage prometnih nesreća",
          startTime: new Date().setHours(17, 47),
          endTime: new Date().setHours(18, 48),
          description:
            "Analiziramo najteže nesreće na hrvatskim prometnicama. S prometnim stručnjakom Damirom Novakom komentiramo svakodnevne greške vozača. U rubrici Svjedočanstva donosimo priču Ivane Smrečki.",
          category: "zabavan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2020-03/709be0df-694a-4052-96ea-c6a1c0.jpg&w=163&h=80",
        },
        {
          id: 53,
          name: "Glas domovine",
          startTime: new Date().setHours(18, 48),
          endTime: new Date().setHours(19, 49),
          description:
            "U emisiji: životna i poslovna priča Ante Budana iz slovenskog Kopra; predstavljen Hrvatski iseljenički zbornik, gošća emisije je urednica Matičinog ljetopisa Vesna Kukavica; kako su izgledala pokladna okupljanja bačkih Hrvata.",
          category: "informativan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2665089a-0fee-440a-9259-6e1721d81d3e.jpg&w=163&h=80",
        },
        {
          id: 54,
          name: "Ko te šiša",
          startTime: new Date().setHours(19, 49),
          endTime: new Date().setHours(20, 35),
          description:
            "Dolazi sudbonosni trenutak kad Božica odluči stati na vagu ne bi li vidjela koliko su se isplatili mjeseci odricanja i kompletna promjena energije. Svi se okupe na tom važnom događaju. Kada vidi da je razlika u 3 dekagrama, Božica dobiva slom živaca.",
          category: "zabavavan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/5a664f67-da34-44ef-ad7e-e990cbd60d96.jpg&w=163&h=80",
        },
        {
          id: 55,
          name: "Priroda i prijateljice",
          startTime: new Date().setHours(20, 35),
          endTime: new Date().setHours(21, 29),
          description:
            "Sandi Toksvig i Judi Love, komičarka i televizijska autorica, otići će u Cumbriju i odsjesti u tri spektakularne i jedinstvene kuće. Šetat će dolinama, planinariti brdima i ploviti čamcem na glasovitim jezerima.",
          category: "zabavan program",
          isReplay: true,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2022-11/0ae40e08-d2f5-493a-a382-937230.jpg&w=163&h=80",
        },
        {
          id: 56,
          name: "Veliki bijeg",
          startTime: new Date().setHours(21, 29),
          endTime: new Date().setHours(22, 21),
          description:
            "Druga epizoda dokumentarne serije koja rekonstruira planiranje i provedbu jednog od najhrabrijih pothvata tijekom Drugog svjetskog rata - bijeg iz Stalaga Luft III. Stotine savezničkih vojnika riskirale su život kako bi se suprotstavile Hitleru.",
          category: "informativan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2024-02/badbdc3b-3f76-4892-a76e-529128.jpg&w=163&h=80",
        },
        {
          id: 57,
          name: "1917",
          startTime: new Date().setHours(22, 21),
          endTime: new Date().setHours(24, 20),
          description:
            "Tijekom I. svjetskog rata dva mlada vojnika dobiju naizgled nemoguć zadatak.",
          category: "film",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2019-12/2a9b448c-67ed-4e56-8a54-464d62.jpg&w=163&h=80",
        },
        {
          id: 58,
          name: "Dolina sreće",
          startTime: new Date().setHours(24, 20),
          endTime: new Date().setHours(25, 17),
          description:
            "Catherine doznaje za bolnu izdaju bliske osobe, a Faisal se nalazi pod sve većim pritiskom sa svih strana.",
          category: "serija",
          season: 1,
          episode: 2,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/d2bc7916-bf54-4921-81d0-71dbe6d345fe.jpg&w=163&h=80",
        },
        {
          id: 59,
          name: "Novi stari slučajevi",
          startTime: new Date().setHours(25, 17),
          endTime: new Date().setHours(26, 17),
          description:
            "Tenzije između Neda i Sashe rastu. Prisiljeni su raditi zajedno kad se posumnja da je smrt filmskog kritičara, čije je tijelo pronađeno u kanalu, povezana s 20 godina starim ubojstvom konceptualnog umjetnika Davida Strake. Dok ispituje Strakine koleg.",
          category: "serija",
          season: 1,
          episode: 5,
          isReplay: true,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/6401b6fb-c563-4e0b-baa0-11b70135ccc1.jpg&w=163&h=80",
        },
        {
          id: 60,
          name: "Art a la carte",
          startTime: new Date().setHours(26, 17),
          endTime: new Date().setHours(26, 48),
          description:
            "Više od pukog kulturnog pregleda! Od ponedjeljka do četvrtka, pola sata, uživo pratimo kulturne događaje i fenomene iz likovne umjetnosti, klasične glazbe, književnosti, kazališta, plesa, arhitekture i dizajna, popularne glazbe, filma. Problematizira.",
          category: "informativan program",
          isReplay: true,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2017-10/7e941b00-93c1-4fa7-955b-c3618d.jpg&w=163&h=80",
        },
        {
          id: 100,
          name: "Nema informacija",
          startTime: new Date().setHours(26, 48),
          endTime: new Date().setHours(29, 5),
          category: "nema informacija",
        },
      ],
    },
    {
      name: "doma",
      broadcasted: [
        {
          id: 100,
          name: "Nema informacija",
          startTime: new Date().setHours(1),
          endTime: new Date().setHours(17, 37),
          category: "nema informacija",
        },
        {
          id: 61,
          name: "Joker",
          startTime: new Date().setHours(17, 37),
          endTime: new Date().setHours(18, 47),
          description:
            "U drugoj epizodi novog kviza ''Joker'' zaigrat će umirovljenica Doris Vlah iz Opatije. Po struci je trgovkinja, no njezina najveća strast je kuhanje, pa preko ljeta radi i kao privatni chef u vilama.",
          category: "zabavan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-11/4fa3ad33-5654-43dd-841e-324612.jpg&w=163&h=80",
        },
        {
          id: 62,
          name: "Dnevnik Nove TV",
          startTime: new Date().setHours(18, 47),
          endTime: new Date().setHours(20, 20),
          description:
            "Najgledanija središnja informativna emisija u zemlji gledateljima svake večeri donosi najvažnije i najrelevantnije informacije iz zemlje i svijeta. Propušteni Dnevnik Nove TV pogledajte na novatv.hr.",
          category: "informativan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2017-06/11ed05da-0a11-4584-930a-e1e80d.jpg&w=163&h=80",
        },
        {
          id: 63,
          name: "Kumovi",
          startTime: new Date().setHours(20, 20),
          endTime: new Date().setHours(21, 25),
          description:
            "Vedrana se nađe u problemu te je suočena sa teškim odlukama. Nakon mnogo razmišljanja, odlučuje razgovarati i sa Zlatanom, no Zlatan je preduhitri te joj kaže da ide s Terezom u Milano. Anđela pak poludi kad čuje Lucu i Janka da odgađaju vjenčanje.",
          category: "serija",
          season: 3,
          episode: 32,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2022-01/5b9afebf-1d85-44b4-8e77-c55f8c.jpg&w=163&h=80",
        },
        {
          id: 64,
          name: "Zlatni kavez",
          startTime: new Date().setHours(21, 25),
          endTime: new Date().setHours(22, 16),
          description:
            "Nakon niza neočekivanih događaja, Kazim radi veliki preokret. Nakon što majci Esme pozli, Sejran će morati progutati svoj ponos i poći s Feritom koji ju je ponovno čekao cijelu noć.",
          category: "serija",
          season: 2,
          episode: 42,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-05/78fc96b5-e5bf-4b57-b162-f526a2.jpg&w=163&h=80",
        },
        {
          id: 65,
          name: "Oproštajno pismo",
          startTime: new Date().setHours(22, 16),
          endTime: new Date().setHours(23, 25),
          description:
            "U domu obitelji Karli, atmosfera je napeta dok Nevzat i najbliži iščekuju ključne vijesti. Hatidže gubi kontrolu nad svojim osjećajima kada čuje nove informacije, obuzeta nevjerojatnim bijesom. S druge strane, Asli dobiva neočekivano dobre vijesti.",
          category: "serija",
          season: 1,
          episode: 42,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-12/f2a3bf09-809b-4979-9554-304719.jpg&w=163&h=80",
        },
        {
          id: 66,
          name: "Večernje vijesti",
          startTime: new Date().setHours(23, 25),
          endTime: new Date().setHours(24, 12),
          description:
            "Pregled najvažnijih informacija iz zemlje i svijeta gledatelji mogu pratiti u Vijestima u 14 i 17 sati te u Večernjim vijestima. Propuštene Vijesti Nove TV pogledajte na novatv.hr.",
          category: "informativni program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/560cf524-143c-4017-b313-2499256ee903.jpg&w=163&h=80",
        },
        {
          id: 67,
          name: "21 Jump street",
          startTime: new Date().setHours(24, 12),
          endTime: new Date().setHours(25, 54),
          description:
            "Odred mladolikih policajaca ubačen je u srednju školu kako bi stali na kraj moćnom dileru.",
          category: "film",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/93ebe664-27f5-4eb8-87a5-032b7f6fb419.jpg&w=163&h=80",
        },
        {
          id: 68,
          name: "Mjesto usijanja",
          startTime: new Date().setHours(25, 54),
          endTime: new Date().setHours(27, 25),
          description:
            "Neočekivani dvojac mora zajednički nadmudriti zločince i spasiti grad od bombaških napada.",
          category: "program za odrasle",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-01/a28a695a-e7cd-40f4-bebd-a3ef60.jpg&w=163&h=80",
        },
        {
          id: 69,
          name: "Astro savjetnik",
          startTime: new Date().setHours(27, 25),
          endTime: new Date().setHours(28, 25),
          description:
            "Naši voditelji su vrhunski stručnjaci koji su se godinama usavršavali i trenirali svoje prirodno urođene sposobnosti da saznaju istinu za druge ljude!",
          category: "program za odrasle",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/719708dc-9f9d-4cde-a9ee-25fd793edf77.jpg&w=163&h=80",
        },
        {
          id: 70,
          name: "Crna lista",
          startTime: new Date().setHours(28, 25),
          endTime: new Date().setHours(29, 5),
          description: "Tko je na tvojoj crnoj listi?",
          category: "serija",
          season: 5,
          episode: 8,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/fbb8891b-2d47-4dd2-b017-c7806eea057e.jpg&w=163&h=80",
        },
      ],
    },
    {
      name: "rtl 2",
      broadcasted: [
        {
          id: 100,
          name: "Nema informacija",
          startTime: new Date().setHours(1),
          endTime: new Date().setHours(17, 5),
          category: "nema informacija",
        },
        {
          id: 71,
          name: "Dođi, pogodi, osvoji",
          startTime: new Date().setHours(17, 5),
          endTime: new Date().setHours(17, 55),
          description:
            "Plinko, Jedna je prava, Sreća u vreći ili, pak, Veliko kolo – nema puno Hrvata koji barem jednom ispred malih ekrana zajedno s kandidatima nisu zaigrali ove i mnoge druge dinamične igre te pogađali cijene u game showu 'Dođi, pogodi, osvoji!'",
          category: "zabavan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2021-10/f3bb0740-9bff-418e-8ab5-867387.jpg&w=163&h=80",
        },
        {
          id: 72,
          name: "Večera za 5",
          startTime: new Date().setHours(17, 55),
          endTime: new Date().setHours(19, 4),
          description:
            "Gledatelje očekuje nova porcija domaćih obroka i zanimljivih kulinarskih trikova uz lepezu raskošnih karaktera iz svih dijelova Hrvatske. Kulinarsko putovanje Hrvatskom vodi gledatelje u dvije županiju - Varaždinsku i Međimursku.",
          category: "zabavan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-08/d2fbaa29-7fba-4811-9017-d4fd6b.jpg&w=163&h=80",
        },
        {
          id: 73,
          name: "RTL danas",
          startTime: new Date().setHours(19, 4),
          endTime: new Date().setHours(20, 25),
          description:
            "RTL Danas svakog dana donosi samo aktualne, istinite i objektivne informacije. Uz etablirano uredništvo i voditelje, RTL Danas je prvi, neovisan i nepristran informativni program.",
          category: "informativni program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2017-09/a4e0acfa-d967-4857-93b0-c59326.jpg&w=163&h=80",
        },
        {
          id: 74,
          name: "San snova",
          startTime: new Date().setHours(20, 25),
          endTime: new Date().setHours(21, 11),
          description:
            "Nakon spektakularne pobjede protiv Pučkog klub je u euforiji, ali vijesti vezane za Alena promijenit će atmosferu. Hoće li se Maji vratiti povjerenje u Alena? Mirko se sve dublje zakopava u svojim lažima, a sa sobom povlači i klub. ",
          category: "serija",
          season: 1,
          episode: 4,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-08/8866ee6f-e3a4-4b18-b5b3-8cbf7d.jpg&w=163&h=80",
        },
        {
          id: 75,
          name: "Brak na prvu",
          startTime: new Date().setHours(21, 11),
          endTime: new Date().setHours(22, 22),
          description:
            "Pet je parova na prvoj ceremoniji odluke odlučilo ostati u sociološkom eksperimentu, a na površinu su izašle emocije, simpatije i razočaranja. Klara i Lovre posljednji su par koji će se suočiti sa stručnjacima.",
          category: "zabavan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2020-03/ed67ece0-2c54-43f4-bdc1-48144a.jpg&w=163&h=80",
        },
        {
          id: 76,
          name: "RTL Direkt",
          startTime: new Date().setHours(22, 22),
          endTime: new Date().setHours(23),
          description:
            "Od ponedjeljka do četvrtka u večernjem terminu Mojmira Pastorčić najvažnije dnevne događaje donosi direktno i sa stavom. RTL Direkt je prisutan svugdje i izvještava o svemu, s vama i za vas – naše gledatelje.",
          category: "informativan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2017-09/55b5966a-bef4-4be5-a408-440866.jpg&w=163&h=80",
        },
        {
          id: 77,
          name: "Tightrope (1984)",
          startTime: new Date().setHours(23),
          endTime: new Date().setHours(25, 1),
          description:
            "Policijski detektiv koji živi kao samohrani otac hvata serijskog ubojicu prostitutki.",
          category: "film",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/132b6a30-376e-49cc-ab25-a5b780bed415.jpg&w=163&h=80",
        },
        {
          id: 78,
          name: "Zločinački umovi",
          startTime: new Date().setHours(25, 1),
          endTime: new Date().setHours(25, 47),
          description:
            "Istražitelji su u lovu na serijskog ubojicu na Floridi, čiji je identitet poznat policiji, koja ga nije uspjela uloviti jer stalno mijenja izgled. Takav način djelovanja omogućava mu da bira slučajne žrtve koje onda muči u hotelskim sobama.",
          category: "serija",
          season: 3,
          episode: 5,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2017-06/ff6469a3-3af6-4a34-b437-3025b1.jpg&w=163&h=80",
        },
        {
          id: 79,
          name: "Zločinački umovi",
          startTime: new Date().setHours(25, 47),
          endTime: new Date().setHours(26, 34),
          description:
            "Istražitelji surađuju s CIA-om u njenim uredima u Virginiji kako bi razotkrili izdajicu u srcu organizacije. Curenje informacija stavlja u opasnost ljude na terenu pa je pronalazak „krtice“ hitan prioritet.",
          category: "serija",
          season: 3,
          episode: 6,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2017-06/ff6469a3-3af6-4a34-b437-3025b1.jpg&w=163&h=80",
        },
        {
          id: 80,
          name: "Zločinački umovi",
          startTime: new Date().setHours(26, 34),
          endTime: new Date().setHours(27, 25),
          description:
            "Istražitelji se nalaze na zasluženom odmoru na različitim lokacijama, gdje svaki od njih dobiva poruku od psihotičnog ubojice, opsjednutog legendom o kralju Arthuru te ih izaziva da pronađu i spase osobu koju je on označio kao sljedeću žrtvu.",
          category: "serija",
          season: 3,
          episode: 7,
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2017-06/ff6469a3-3af6-4a34-b437-3025b1.jpg&w=163&h=80",
        },
        {
          id: 100,
          name: "Nema informacija",
          startTime: new Date().setHours(27, 25),
          endTime: new Date().setHours(29, 5),
          category: "nema informacija",
        },
      ],
    },
  ],
  categories: [
    "serija",
    "film",
    "zabavan program",
    "informativan program",
    "dokumentarni program",
    "program za odrasle",
  ],
  watchlist: [],
  pin: "12345678",
};
