export const data = {
  programs: [
    {
      name: "hrt 1",
      broadcasted: [
        {
          id: 1,
          name: "Potjera",
          startTime: new Date().setHours(18, 17),
          endTime: new Date().setHours(18, 59),
          description:
            "U 'Potjeri' četiri natjecatelja odgovaraju na pitanja općeg znanja i istovremeno grade taktiku koja će ih dovesti do finalnog kruga. Međutim, na putu im stoji Lovac. Taj će (ne)uobičajeni protivnik u uzbudljivoj igri znanja i brzine pokušati natjecatelje, jednog po jednog, izbaciti iz igre i onemogućiti ih da osvoje desetke tisuća kuna.",
          category: "zabavan program",
          isReplay: false,
          score: 4.8,
          img: "https://mojtv.hr/thumb.ashx?path=/images/846c5f56-60a0-412c-9106-f3fe0c7697cb.jpg&w=491&h=250",
        },
        {
          id: 2,
          name: "Dnevnik 2",
          startTime: new Date().setHours(19),
          endTime: new Date().setHours(20, 15),
          description:
            "Najvažnije vijesti iz zemlje i svijeta, brojne reportaže, gostovanja istaknutih stručnjaka i komentatora u Dnevniku 2, u najgledanijoj informativnoj emisiji HTV-a. Uz sportske aktualnosti pogledajte i detaljnu vremensku prognozu za sljedeće dane.",
          category: "informativan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/4637d205-88ac-4810-b163-56a1b5f80655.jpg&w=491&h=250",
        },
        {
          id: 3,
          name: "What's up Sjever-Jug",
          startTime: new Date().setHours(20, 16),
          endTime: new Date().setHours(21, 14),
          description:
            "Kada su se u 19. stoljeću razdvajale Danska i Norveška, vojno jača Danska dobila je Grenland, ledeni otok, ali ipak čvrsto tlo, dok je Norveškoj pripalo Sjeverno more. Do danas Danci tuguju zbog te podjele. Saznat ćemo o norveškom fondu nafte i plina.",
          category: "dokumentarni program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2024-02/a4437446-9487-4024-ad25-ca4e86.jpg&w=163&h=80",
        },
        {
          id: 4,
          name: "Fortuna",
          startTime: new Date().setHours(21, 15),
          endTime: new Date().setHours(22, 17),
          description:
            "'La Fortuna' je španjolsko-američka pustolovna serija. Mladi diplomat Álex Ventura predvodi misiju čiji je cilj vratiti olupina broda koju je prisvojio lovac na blago Frank Wild.",
          category: "serija",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-08/843950b1-7768-4169-b427-eaf20a.jpg&w=163&h=80",
        },
        {
          id: 5,
          name: "Otvoreno",
          startTime: new Date().setHours(22, 18),
          endTime: new Date().setHours(22, 54),
          description:
            "Od rezerve do pobjednika Dore! Kako je Baby Lasagna u mjesec dana osvojio publiku, uvjerljivo odnio pobjedu i odmah skočio na drugo mjesto na kladionicama? Hvata li Hrvatska s Baby Lasagnom priliku za pobjedu?",
          category: "informativan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/55f20577-aa30-4643-a90e-3c83fe1f9538.jpg&w=163&h=80",
        },
        {
          id: 6,
          name: "Dnevnik 3",
          startTime: new Date().setHours(22, 55),
          endTime: new Date().setHours(23, 17),
          description:
            "Najnovije vijesti iz zemlje i svijeta te sažeta vremenska prognoza za sljedeći dan.",
          category: "informativan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/1a283d73-b0f7-4725-be50-67883ed9215d.jpg&w=163&h=80",
        },
        {
          id: 7,
          name: "Labirint",
          startTime: new Date().setHours(23, 18),
          endTime: new Date().setHours(23, 45),
          description:
            "Cijene stanova lete u nebo. Mnogim su mladim obiteljima vlastiti stambeni kvadrati daleki san. Istodobno, teško se pronalaze povoljni podstanarski stanovi. Tko kupuje skupe stambene kvadrate? Zašto država ne gradi stanove za najam?",
          category: "informativni program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-11/11ba9aaa-7e59-461c-aa28-0a5fb2.jpg&w=163&h=80",
        },
        {
          id: 8,
          name: "Putin: Ruska špijunska priča",
          startTime: new Date().setHours(23, 45),
          endTime: new Date().setHours(25, 40),
          description:
            "U drugoj epizodi dokumentarne serije vidjet ćemo kako je Vladimir Putin stigao u Kremlj kao ranjivi i nepoznati predsjednik kojega su ruski oligarsi htjeli kontrolirati. Otkrit ćemo kako je učvrstio svoju moć te se na kraju okružio kolegama iz KGB-a.",
          category: "dokumentarni program",
          isReplay: true,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2022-03/19a598ff-7868-4b54-9de5-8f52d2.jpg&w=163&h=80",
        },
        {
          id: 9,
          name: "Potjera",
          startTime: new Date().setHours(25, 41),
          endTime: new Date().setHours(26, 30),
          description:
            "U 'Potjeri' četiri natjecatelja odgovaraju na pitanja općeg znanja i istovremeno grade taktiku koja će ih dovesti do finalnog kruga. Međutim, na putu im stoji Lovac. Taj će (ne)uobičajeni protivnik u uzbudljivoj igri znanja i brzine pokušati natjecatelje, jednog po jednog, izbaciti iz igre i onemogućiti ih da osvoje desetke tisuća kuna.",
          category: "zabavan program",
          isReplay: true,
          score: 4.8,
          img: "https://mojtv.hr/thumb.ashx?path=/images/846c5f56-60a0-412c-9106-f3fe0c7697cb.jpg&w=491&h=250",
        },
        {
          id: 10,
          name: "La Promesa",
          startTime: new Date().setHours(26, 30),
          endTime: new Date().setHours(27, 30),
          description:
            "Blanca odlučuje otići s La Promese i upustiti se u novu pustolovinu, ali prije toga želi reći Manuelu nešto važno. A nešto jednako važno želi reći i Jani. Catalina pokušava upravljati imanjem iz sjene, ali radnici nikako ne žele prihvatiti ženu.",
          category: " serija",
          isReplay: true,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2023-09/058f3981-6cb3-4f71-a098-b342e8.jpg&w=163&h=80",
        },
      ],
    },
    {
      name: "hrt 2",
      broadcasted: [
        {
          id: 11,
          name: "Dom na kvadrat",
          startTime: new Date().setHours(17, 14),
          endTime: new Date().setHours(17, 47),
          description:
            "Dizajnerica interijera Martina Kordić podučit će nas kako neutralne boje u interijeru učiniti zanimljivijima, a Leon Božić predstavlja idealne biljke za male stanove. Donosimo priču o corienu, inovativnom materijalu koji dizajnerima ostvaruje snove.",
          category: "zabavan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2020-04/a8c062ff-7bda-48ee-aca0-c34887.jpg&w=163&h=80",
        },
        {
          id: 12,
          name: "Istrage prometnih nesreća",
          startTime: new Date().setHours(17, 48),
          endTime: new Date().setHours(18, 48),
          description:
            "Analiziramo najteže nesreće na hrvatskim prometnicama. S prometnim stručnjakom Damirom Novakom komentiramo svakodnevne greške vozača. U rubrici Svjedočanstva donosimo priču Ivane Smrečki.",
          category: "zabavan program",
          isReplay: false,
          score: undefined,
          img: "https://mojtv.hr/thumb.ashx?path=/images/2020-03/709be0df-694a-4052-96ea-c6a1c0.jpg&w=163&h=80",
        },
        {
          id: 13,
          name: "",
          startTime: new Date().setHours(20, 16),
          endTime: new Date().setHours(22, 14),
          description: "",
          category: " program",
          isReplay: false,
          score: undefined,
          img: "",
        },
        {
          id: 14,
          name: "",
          startTime: new Date().setHours(20, 16),
          endTime: new Date().setHours(21, 14),
          description: "",
          category: " program",
          isReplay: false,
          score: undefined,
          img: "",
        },
        {
          id: 15,
          name: "",
          startTime: new Date().setHours(20, 16),
          endTime: new Date().setHours(21, 14),
          description: "",
          category: " program",
          isReplay: false,
          score: undefined,
          img: "",
        },
        {
          id: 16,
          name: "",
          startTime: new Date().setHours(20, 16),
          endTime: new Date().setHours(21, 14),
          description: "",
          category: " program",
          isReplay: false,
          score: undefined,
          img: "",
        },
        {
          id: 17,
          name: "",
          startTime: new Date().setHours(20, 16),
          endTime: new Date().setHours(21, 14),
          description: "",
          category: " program",
          isReplay: false,
          score: undefined,
          img: "",
        },
        {
          id: 18,
          name: "",
          startTime: new Date().setHours(20, 16),
          endTime: new Date().setHours(21, 14),
          description: "",
          category: " program",
          isReplay: false,
          score: undefined,
          img: "",
        },
        {
          id: 19,
          name: "",
          startTime: new Date().setHours(20, 16),
          endTime: new Date().setHours(21, 14),
          description: "",
          category: " program",
          isReplay: false,
          score: undefined,
          img: "",
        },
        {
          id: 20,
          name: "",
          startTime: new Date().setHours(20, 16),
          endTime: new Date().setHours(21, 14),
          description: "",
          category: " program",
          isReplay: false,
          score: undefined,
          img: "",
        },
      ],
    },
  ],
  categories: [
    "serija",
    "zabavan program",
    "informativan program",
    "dokumentarni program",
  ],
  watchlist: [],
};
